<?php
namespace Home\Controller;
use Think\Controller;
class LiveController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /*
     * 2016-09-05 网页直播
     * 直播详细
     * */
    public function index(){
        vendor("Pili.Pili");

        $ip=get_client_ip();//获取客户端IP

        $this->assign('ip',$ip);
       /* $this->assign('ip',$ip);*/

        $roomid=$_GET["roomid"];//获取传过来的房间id
        $userinfo = session('userinfo');//获取用户信息

        if($roomid){
            $roominfo=M("rooms")->where("roomid=%d",$roomid)->find();//获取房间信息
            if($roominfo)
            {
                //$this->assign('roominfo',$roominfo);
                //根据roomid去差用户表的用户id
                $users = M("userinfos")->field('userid,nickname,gradeid')->where(array("roomid"=>$roomid))->find();//获取房主用户id，和昵称,等级
                //查询直播大厅表
                $rh = M("livehall")->field('speaker')->where(array("roomid"=>$roomid))->find();
//                $tmp=$roominfo["style"]==""?"Live":$roominfo["style"];//获取直播室页面模板
                $this->assign('users',$users);
                $this->assign('livehall',$rh);
                $this->assign('userinfo',$userinfo);
                $this->assign('list',$roomid);
                $this->assign("roominfo",$roominfo);
				var_dump($roominfo['keywords']);
				var_dump($roominfo['description']);
				exit();
//                $this->display($tmp.":index");
                $this->display("Live:index");
            }
            else
            {
                $this->display("error该房间号不存在");
            }
        }else{
            $this->display("Live:index");
        }
    }


    public function indexz() {
        //获取用户当前ip,测试可以，正式版获取不到

        $ip = get_client_ip(); //获取客户端IP
        $this->assign('ip', $ip);
        $_SESSION["username"] = $_COOKIE["username"];

        /* var_dump($_SESSION["username"]);
          var_dump($_COOKIE["username"]); */
        $row = M("userinfos")->field("headimage,userid,userpwd,username,phone,email,nickname,usergrade,roomid")->where(array("username" => $_COOKIE["username"]))->find();
        $this->assign('headimage', $row['headimage']);
        session("userinfo", $row);
        session('userinfo.userpwd', null);

        vendor("Pili.Pili");
        $roomid = $_GET["roomid"]; //获取传过来的房间的code
        // p($roomid);
        $userinfo = session('userinfo'); //获取用户信息
        //获取用户的userid进行加密
        if ($userinfo) {
            $mm = $this->encode($userinfo['userid']);
        }

        if ($roomid) {
            //$roominfo=M("rooms")->where("roomid=%d",$roomid)->find();//获取房间信息
            $rooms_model = D("rooms");
            $roominfo = $rooms_model->where("roomcode=%d", $roomid)->find(); //根据全局唯一的访问编号获取房间信息
            if ($roominfo) {
                //礼物排行榜
                $webcastid = $_GET["webcastid"];

                //广告展示位show

                $showarea = M('showarea')
                    ->where(array('roomid' => $roominfo['roomid']))
                    ->field('saname,saurl,image')
                    ->order('createtime desc')
                    ->limit(1)
                    ->find();
                // p($showarea);die;
                $this->assign('showarea', $showarea);



                $date = date('Y-m-d'); //获取当前日期
                $month = date('m-d');
                $week = date('w', strtotime($date));
                $weekarray_name=array("日","一","二","三","四","五","六");
                $weekayyay = array();
                for ($i = 1; $i <= 6; $i++) {
                    //如果当前星期小于
                    if ($i < $week) {
                        $weekayyay[$i]["time"] = strtotime($date) - ($week - $i) * 3600 * 24;
                    }

                    if ($i == $week) {

                        $weekayyay[$i]["time"] = time();
                    }

                    if ($i > $week) {
                        $chai = $i - $week;
                        $weekayyay[$i]["time"] = strtotime($date) + $chai * 3600 * 24;
                    }
                    $key = date("w",$weekayyay[$i]["time"]);
                    $weekayyay[$i]["week_name"] = "星期".$weekarray_name[$key];
                }


                $class=$roominfo["class"];
                $classarray=explode(",",$class);

                //var_dump($class);
                //exit();
                $this->assign('class',$classarray);//


                $isprograme = $roominfo["isprograme"];



                //判断房间是否有节目单
                if ($roominfo["isprograme"] == 1) {
                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 1;
                    $programlist1 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 2;
                    $programlist2 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 3;
                    $programlist3 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 4;
                    $programlist4 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 5;
                    $programlist5 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"] = $roominfo['roomid'];
                    $where["weekday"] = 6;
                    $programlist6 = M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                }

                $this->assign('isprograme', $isprograme); //把房间是否需要加载节目列表，传到前台

                $this->assign('programlist1', $programlist1); //把节目单绑定到前台,周一节目单
                $this->assign('programlist2', $programlist2); //周二节目单
                $this->assign('programlist3', $programlist3);
                $this->assign('programlist4', $programlist4);
                $this->assign('programlist5', $programlist5);
                $this->assign('programlist6', $programlist6);

                $this->assign('weekayyay', $weekayyay);


                //$this->assign('roominfo',$roominfo);
                //根据roomid查询用户表的用户信息
                $users = M("userinfos")->field('userid,nickname,gradeid')->where(array("roomid" => $roominfo['roomid']))->find(); //获取房主用户id，和昵称,等级
                //查询直播大厅表返回直播室名称,和主讲
                $rh = M("livehall")->field('speaker,livename')->where(array("roomid" => $roomid))->find();

//                $tmp=$roominfo["style"]==""?"Live":$roominfo["style"];//获取直播室页面模板
                //获取用户是否关注过次房间
                $count = M("userrooms")->field('urid')->where(array("userid" => $userinfo['userid'], "roomid" => $roominfo['roomid']))->count();
                //当前房间被关注的总数
                $gzcount = M("userrooms")->field('urid')->where(array("roomid" => $roominfo['roomid']))->count();
                $map['roomid'] = array('neq', $roomid);
                //$livehall = M('livehall')->field('liveid,livename,speaker,thumbnail,hits,liveurl,roomid')->where($map)->limit('7')->select();

                $vadio = M('videos')->Field('title,source,thumb,description,vurl,clickcount,nid')->order('clickcount desc')->limit(8)->select();
                $this->assign('videos', $vadio);
               /* $this->action_log($userinfo['userid'], $ip, 'http://www.9dcj.com/$roomid', '20000002', $roomid, '1', '进直播房间');*/
                // p($livehall);die;
                $this->assign('data', $livehall);
                $this->assign('focus', $count);
                $this->assign('focuscount', $gzcount);
                $this->assign('users', $users);
                //$this->assign('livehall',$rh);
                // 老师列表
                $userteacher = D("userteacher");
                $teacher_list = $userteacher->field("userid,teachname")->where(array("roomid"=>$roominfo["roomid"]))->select();

                $this->assign("teacher_list", $teacher_list);

                // 礼物列表
                $gift_list = array(
                    array("gift_name"=>"鲜花","gift_id"=>101,"gift_money"=>3,"image_name"=>"gift/101.gif"),
                    array("gift_name"=>"点赞","gift_id"=>102,"gift_money"=>1,"image_name"=>"gift/102.gif"),
                    array("gift_name"=>"香槟","gift_id"=>103,"gift_money"=>66,"image_name"=>"gift/103.gif"),
                    array("gift_name"=>"话筒","gift_id"=>104,"gift_money"=>90,"image_name"=>"gift/104.gif"),
                    array("gift_name"=>"财气冲天","gift_id"=>105,"gift_money"=>880,"image_name"=>"gift/105.gif"),
                    array("gift_name"=>"法拉利","gift_id"=>106,"gift_money"=>1800,"image_name"=>"gift/106.gif"),
                    array("gift_name"=>"礼花","gift_id"=>107,"gift_money"=>180,"image_name"=>"gift/107.gif"),
                    array("gift_name"=>"财神","gift_id"=>108,"gift_money"=>360,"image_name"=>"gift/108.gif"),
                    array("gift_name"=>"掌声","gift_id"=>109,"gift_money"=>1,"image_name"=>"gift/109.gif"),
                    array("gift_name"=>"游艇","gift_id"=>110,"gift_money"=>2400,"image_name"=>"gift/110.gif"),
                    array("gift_name"=>"茅台","gift_id"=>111,"gift_money"=>166,"image_name"=>"gift/111.gif"),
                    array("gift_name"=>"神算子","gift_id"=>112,"gift_money"=>60,"image_name"=>"gift/112.gif"),
                );
                $this->assign("gift_list",$gift_list);


                // 房间二维码
                $qrcode_imageurl = D("Qrcode")->where(array("roomid"=>$roominfo["roomid"]))->order("rand()")->getField("imgurl");
                $this->assign("qrcode_imageurl",$qrcode_imageurl);

                //绑定用户信息
                $this->assign("userinfo", $row);
                $this->assign('userinfo1', $userinfo);
                $this->assign('userinfo', $userinfo['nickname']);
                $this->assign('list', $roominfo['roomid']);
                $this->assign('zbid', $mm);
                $this->assign("roominfo", $roominfo);
                /*
                  var_dump($roominfo);
                  exit(); */
                //获取直播室的页面风格
                if ($roominfo["style"] == "Livestyle1") {
                    //判断当前房间的类型是机构还是个人决定跳转到那个页面
                    if ($roominfo["roomtype"] == 1) {
                        $this->display("Live/Livestyle1:indexz"); //机构
                    } else {
//                        var_dump($roominfo["roomtype"]);
                        $this->display("Live:aindex"); //个人
                    }
                }elseif($roominfo["style"] == "Livestyle2") {
                    //判断当前房间的类型是机构还是个人决定跳转到那个页面
                    if ($roominfo["roomtype"] == 1) {
                        $this->display("Live:aindex"); //个人
                    }else{
                        $this->display("Live:aindex");
                    }
                } else {
                    //判断当前房间的类型是机构还是个人决定跳转到那个页面
                    if ($roominfo["roomtype"] == 1) {
                        $this->display("Live:indexz"); //个人
                    } else {
                        $this->display("Live:cindex"); //个人
                    }
                }
            } else {
                $this->display("error该房间号不存在");
            }
        } else {
            $this->display("Live:indexz");
        }
    }
	
	public function indexzz(){
		$_SESSION["username"]=$_COOKIE["username"];

        $row = M("userinfos")->field("userid,userpwd,username,phone,email,nickname,usergrade,roomid")->where(array("username"=>$_COOKIE["username"]))->find();
        session("userinfo",$row);
        session('userinfo.userpwd',null);
		
		
        vendor("Pili.Pili");
        $roomid=$_GET["roomid"];//获取传过来的房间的code
        // p($roomid);
        $userinfo = session('userinfo');//获取用户信息
        if($roomid){
            //$roominfo=M("rooms")->where("roomid=%d",$roomid)->find();//获取房间信息
			$roominfo=M("rooms")->where("roomcode=%d",$roomid)->find();//根据全局唯一的访问编号获取房间信息
			
            if($roominfo)
            {
               //礼物排行榜

                $webcastid=$_GET["webcastid"];

               /* var_dump($webcastid);
                exit();*/






                //广告展示位show

                $showarea=M('showarea')
                        ->where(array('roomid'=>$roomid))
                        ->field('saname,saurl')
                        ->select();
                          // p($showarea);die;



                $date=date('Y-m-d');//获取当前日期
                $month=date('m-d');
                $week=date('w',strtotime($date));
                $weekayyay=array();
                for($i=1;$i<=6;$i++){
                   //如果当前星期小于
                   if($i<$week){
                       $weekayyay[$i]=date("m-d",(strtotime($date) - ($week-$i)*3600*24));
                    }

                    if($i==$week){

                        $weekayyay[$i]=date('m-d');
                    }

                    if($i>$week){
                        $chai=$i-$week;
                        $weekayyay[$i]=date("m-d",(strtotime($date) + $chai*3600*24));
                    }
                }



                $isprograme=$roominfo["isprograme"];
               //判断房间是否有节目单
                if($roominfo["isprograme"]==1){
                    $where["roomid"]=$roominfo['roomid'];
                        $where["weekday"]=1;
                        $programlist1=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"]=$roominfo['roomid'];
                    $where["weekday"]=2;
                    $programlist2=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"]=$roominfo['roomid'];
                    $where["weekday"]=3;
                    $programlist3=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                    $where["roomid"]=$roominfo['roomid'];
                    $where["weekday"]=4;
                    $programlist4=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                    $where["roomid"]=$roominfo['roomid'];
                    $where["weekday"]=5;
                    $programlist5=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"]=$roominfo['roomid'];
                    $where["weekday"]=6;
                    $programlist6=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();
                }

                $this->assign('isprograme',$isprograme);//把房间是否需要加载节目列表，传到前台

                $this->assign('programlist1',$programlist1);//把节目单绑定到前台,周一节目单
                $this->assign('programlist2',$programlist2);//周二节目单
                $this->assign('programlist3',$programlist3);
                $this->assign('programlist4',$programlist4);
                $this->assign('programlist5',$programlist5);
                $this->assign('programlist6',$programlist6);

                $this->assign('weekayyay',$weekayyay);


                //$this->assign('roominfo',$roominfo);
                //根据roomid查询用户表的用户信息
                $users = M("userinfos")->field('userid,nickname,gradeid')->where(array("roomid"=>$roominfo['roomid']))->find();//获取房主用户id，和昵称,等级
                //查询直播大厅表返回直播室名称,和主讲
                $rh = M("livehall")->field('speaker,livename')->where(array("roomid"=>$roomid))->find();

//                $tmp=$roominfo["style"]==""?"Live":$roominfo["style"];//获取直播室页面模板
                //获取用户是否关注过次房间
                $count=M("userrooms")->field('urid')->where(array("userid"=>$userinfo['userid'],"roomid"=>$roominfo['roomid']))->count();
                //当前房间被关注的总数
                $gzcount=M("userrooms")->field('urid')->where(array("roomid"=>$roominfo['roomid']))->count();
                $map['roomid'] = array('neq',$roomid);
                //$livehall = M('livehall')->field('liveid,livename,speaker,thumbnail,hits,liveurl,roomid')->where($map)->limit('7')->select();
                $vadio = M('videos')->Field('title,source,thumb,description,vurl,clickcount,nid')->order('clickcount desc')->limit(8)->select();
                $this->assign('videos',$vadio);
                // p($livehall);die;
                $this->assign('data',$livehall);
                $this->assign('focus',$count);
                $this->assign('focuscount',$gzcount);
                $this->assign('users',$users);
                //$this->assign('livehall',$rh);
				//绑定用户信息
				$this->assign("userinfo",$row);
                $this->assign('userinfo1',$userinfo);
                $this->assign('userinfo',$userinfo['nickname']);
                $this->assign('list',$roominfo['roomid']);
                $this->assign("roominfo",$roominfo);
                $this->assign('showarea',$showarea);
                //获取直播室的页面风格
                if($roominfo["style"]=="Livestyle1"){
                    //判断当前房间的类型是机构还是个人决定跳转到那个页面
                    if($roominfo["roomtype"]==1){
                        $this->display("Live/Livestyle1:indexz");//机构
                    }else{
//                        var_dump($roominfo["roomtype"]);
                        $this->display("Live:cindex");//个人
                    }
                }else{
                    //判断当前房间的类型是机构还是个人决定跳转到那个页面
                    if($roominfo["roomtype"]==1){
                        $this->display("Live:indexz");//个人
                    }else{
                        $this->display("Live:cindex");//个人
                    }
                }
            }
            else
            {
                $this->display("error该房间号不存在");
            }
        }else{
            $this->display("Live:indexz");
        }
    }





    public function indexs(){
        vendor("Pili.Pili");
        $roomid=$_GET["roomid"];//获取传过来的房间id
        $userinfo = session('userinfo');//获取用户信息
        if($userinfo){
            $mm = $this->encode($userinfo['userid']);
        }
        if($roomid){
            $roominfo=M("rooms")->where("roomid=%d",$roomid)->find();//获取房间信息
            if($roominfo)
            {

                $date=date('Y-m-d');//获取当前日期
                $month=date('m-d');
                $week=date('w',strtotime($date));

                $weekayyay=array();
                for($i=1;$i<=6;$i++){
                    //如果当前星期小于
                    if($i<$week){
                        $weekayyay[$i]=date("Y-m-d",(strtotime($date) - $i*3600*24));
                    }

                    if($i==$week){

                        $weekayyay[$i]=date('Y-m-d');
                    }

                    if($i>$week){
                        $chai=$i-$week;
                        $weekayyay[$i]=date("Y-m-d",(strtotime($date) + $chai*3600*24));
                    }


                }

                /*var_dump($weekayyay);*/

                $isprograme=$roominfo["isprograme"];
                //判断房间是否有节目单
                if($roominfo["isprograme"]==1){
                    $where["roomid"]=$roomid;
                    $where["weekday"]=1;
                    $programlist1=M("programmenu")
                        ->where($where)
                        ->order('sort desc')
                        ->select();

                    $where["roomid"]=$roomid;
                    $where["weekday"]=2;
                    $programlist2=M("programmenu")
                        ->where($where)
                        ->order('sort desc')
                        ->select();

                    $where["roomid"]=$roomid;
                    $where["weekday"]=3;
                    $programlist3=M("programmenu")
                        ->where($where)
                        ->order('sort desc')
                        ->select();
                    $where["roomid"]=$roomid;
                    $where["weekday"]=4;
                    $programlist4=M("programmenu")
                        ->where($where)
                        ->order('sort desc')
                        ->select();
                    $where["roomid"]=$roomid;
                    $where["weekday"]=5;
                    $programlist5=M("programmenu")
                        ->where($where)
                        ->order('sort asc')
                        ->select();

                    $where["roomid"]=$roomid;
                    $where["weekday"]=6;
                    $programlist6=M("programmenu")
                        ->where($where)
                        ->order('sort desc')
                        ->select();
                }



                $this->assign('isprograme',$isprograme);//把房间是否需要加载节目列表，传到前台

                $this->assign('programlist1',$programlist1);//把节目单绑定到前台,周一节目单
                $this->assign('programlist2',$programlist2);//周二节目单
                $this->assign('programlist3',$programlist3);
                $this->assign('programlist4',$programlist4);
                $this->assign('programlist5',$programlist5);
                $this->assign('programlist6',$programlist6);

                $this->assign('weekayyay',$weekayyay);


                $this->assign('roominfo',$roominfo);
                //根据roomid查询用户表的用户信息
                $users = M("userinfos")->field('userid,nickname,gradeid')->where(array("roomid"=>$roomid))->find();//获取房主用户id，和昵称,等级
                //查询直播大厅表返回直播室名称,和主讲
                $rh = M("livehall")->field('speaker,livename')->where(array("roomid"=>$roomid))->find();
//                $tmp=$roominfo["style"]==""?"Live":$roominfo["style"];//获取直播室页面模板
                //获取用户是否关注过次房间
                $count=M("userrooms")->field('urid')->where(array("userid"=>$userinfo['userid'],"roomid"=>$roomid))->count();
                //当前房间被关注的总数
                $gzcount=M("userrooms")->field('urid')->where(array("roomid"=>$roomid))->count();
                $map['roomid'] = array('neq',$roomid);
                $livehall = M('livehall')->field('liveid,livename,speaker,thumbnail,hits,liveurl,roomid')->where($map)->limit('7')->select();
                $vadio = M('videos')->Field('title,source,thumb,description,vurl,clickcount,nid')->order('clickcount desc')->limit(8)->select();
                $this->assign('videos',$vadio);
                // p($livehall);die;
                $this->assign('data',$livehall);
                $this->assign('focus',$count);
                $this->assign('focuscount',$gzcount);
                $this->assign('users',$users);
                $this->assign('livehall',$rh);
                $this->assign('userinfo1',$userinfo);
                $this->assign('userinfo',$userinfo['nickname']);
                $this->assign('list',$roomid);
                $this->assign("roominfo",$roominfo);
                $this->assign('zbid',$mm);
                //获取直播室的页面风格
                if($roominfo["style"]=="Livestyle1"){
                    $this->display("Live/Livestyle1:indexz");
                }else{
                    $this->display("Live:indexz");
                }
            }
            else
            {
                $this->display("error该房间号不存在");
            }
        }else{
            $this->display("Live:index");
        }

    }

    /**
     * 简单对称加密算法之加密
     * @param String $string 需要加密的字串
     * @param String $skey 加密EKY
     * @author Anyon Zou <zoujingli@qq.com>
     * @date 2013-08-13 19:30
     * @update 2014-10-10 10:10
     * @return String
     */
    public function encode($string = '', $skey = '9dcjhaoyuezhibojiami') {
        $strArr = str_split(base64_encode($string));
        $strCount = count($strArr);
        foreach (str_split($skey) as $key => $value)
            $key < $strCount && $strArr[$key].=$value;
        return str_replace(array('=', '+', '/'), array('O0O0O', 'o000o', 'oo00o'), join('', $strArr));
    }

    /*
     * 关注
     * */
    public function concern()
    {
        $roomid = I('post.roomid');
        $userid = session('userinfo.userid');
        $userrooms = M('userrooms');
        if (!empty($roomid)) {
            if (empty($userid)) {
                $this->ajaxReturn(false);
            } else {
                //判断是否关注过s
//                $count=M("userrooms")->field('urid')->where(array("userid"=>$userinfo['userid'],"roomid"=>$roomid))->count();
//                if($count){
//                    $this->ajaxReturn("已经关注过此房间");
//                }
                $data1['userid'] = $userid;
                $data1['roomid'] = $roomid;
                $data1['isenable'] = 1;
                $data = $userrooms->data($data1)->add();
                $this->ajaxReturn($data);
            }
        }
    }
    /*
     * 取消关注
     * */
     public function concel()
    {
        $roomid = I('post.roomid');
        $rtype = I('get.type');
        $userid = session('userinfo.userid');

        $userrooms = M('userrooms');
        if (!empty($roomid)) {
            if (empty($userid)) {
                $this->ajaxReturn(false);
            } else {
                $isenable = $userrooms->where(array('roomid'=>$roomid, 'userid'=>$userid))->field('isenable')->find();
                if ($isenable) {
                    
                $data = $userrooms->where(array('roomid'=>$roomid, 'userid'=>$userid))->delete();
                if($rtype==2){
                    $this->redirect("Subscribe/subscribe");
                }else{
                    $this->ajaxReturn($data);
                }

                }
            }
        }
    }



//用户举报处理 2016-09-20 sjy
    public function report(){

        $roomid=$_GET["roomid"];//获取传过来的房间id*/

        $this->assign("roomid",$roomid);
        $this->display("Live:report");

    }



    public function candel(){

        $roomid=$_GET["roomid"];//获取传过来的房间id*/

        /*  $roomid=1;*/
        $userinfo = session('userinfo');//获取用户信息
        $userid=$userinfo["userid"];
        $usertel=$_POST["usertel"];
        $reason=$_POST["reason"];


        if (empty($usertel)) {

            $this->error("用户联系电话不能为空");
        }

        if (empty($reason)) {

            $this->error("举报原因不能为空");
        }

        $where["userid"]=$userid;
        $where["roomid"]=$roomid;
        $where["usertel"]=$usertel;
        $where["reason"]=$reason;

        $result=M("report")
            ->data($where)
            ->add();

        if($result){
            $this->display("Live:shsuccess");

            //举报成功后进行页面跳转
        }else{
            $this->error("举报失败");
        }





    }


//新的排行榜
    public function gift() {
        $roomid = $_GET["roomid"];
        $usergift = D("usergift");
        $userinfos = D('userinfos');
        $type = I('get.type');
        switch ($type) {
            case 1:
                $start = date("Y-m-d H:i:s",mktime(0,0,0,date('m'),date('d'),date('Y')));
                $end = date("Y-m-d H:i:s",mktime(0,0,0,date('m'),date('d')+1,date('Y'))-1);
                $where['createtime'] = array('between', $start . "," . $end);
                break;
            case 2:
                //最近7日
                $start = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m"), -5, date("Y")));
                //$start = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m"), date("d") - date("w") + 1, date("Y")));
                $end = date("Y-m-d H:i:s");
                $where['createtime'] = array('between', $start . "," . $end);
                break;
            case 3:
                //最近三十日
                $start = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m"), -29, date("Y")));
                //$end = date("Y-m-d H:i:s", mktime(23, 59, 59, date("m"), date("t"), date("Y")));
                $end = date("Y-m-d H:i:s");
                $where['createtime'] = array('between', $start . "," . $end);
                break;
            default:
                //参数错误
                $this->ajaxReturn(array("info"=>"parameter error","status"=>400,"list"=>null));
                exit;
                break;
        }
        if($roomid){
            $where["roomid"] = $roomid;
        }else{
            //参数错误
            $this->ajaxReturn(array("info"=>"not roomid","status"=>402,"list"=>null));
            exit;
        }
        $data = $usergift
            ->where($where)
            ->field('frmuserid')
            ->distinct(true)
            ->select();
        $gift_array = array();

        if(empty($data)){
            //数据为空
            $this->ajaxReturn(array("info"=>"not data","status"=>401,"list"=>null));
            exit;
        }

        foreach ($data as $key => $value) {
            $user = $userinfos
                ->field('nickname,headimage,gradename,gradenum')
                ->join('wht_grade on wht_userinfos.gradeid=wht_grade.gradeid')
                ->where(array('wht_userinfos.userid' => $value['frmuserid']))
                ->find();
            $user["nickname"] = is_username_number($user["nickname"]);
            $gift_array[$key]['user_index'] = $user;
            $gift_array[$key]['sum_grade'] = $usergift
                //->field('SUM(total) as zong')
                ->where(array('frmuserid' => $value['frmuserid']))
                ->where($where)
                ->limit(10)
                ->getField("SUM(total)");
            $price[$key] = $gift_array[$key]['sum_grade'];
            $gift_array[$key]["frmuserid"] = $value["frmuserid"];
        }

        array_multisort($price, SORT_NUMERIC, SORT_DESC, $gift_array);

        $this->ajaxReturn(array("info"=>"success","status"=>200,"list"=>$gift_array));
        //$data = $usergift->field('SUM(giftprice) as zong')->where(array('frmuserid'=>48,'roomid'=>$roomid))->order('SUM(giftprice) DESC')->limit(10)->fetchSql(true)->find();
    }




}